WITH U2021 AS (
    -- 2021년에 가입한 사용자만 필터링
    SELECT USER_ID 
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), SALES AS (
    -- 구매 내역이 있는 사용자 중 2021년 가입자만 필터링
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM U2021)
)
SELECT 
    S.YEAR, 
    S.MONTH, 
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM U2021), 1) AS PURCHASED_RATIO
FROM SALES S
GROUP BY S.YEAR, S.MONTH
ORDER BY S.YEAR, S.MONTH;